### ISSUE TITLE
Multiple outputs?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/barback#1]
Hello,

I got a little confused about the documentation of the addOutput method:

 /// Stores [output] as the output created by this transformation.
  ///
  /// A transformation can output as many assets as it wants.
  void addOutput(Asset output) {
    // TODO(rnystrom): This should immediately throw if an output with that ID
    // has already been created by this transformer.
    _outputs.add(output);
  }

Reading the dartdoc, there's support for two interpretations: "There is exactly or at most one output asset per transformation", based on the wording '_the_ output created'; the other interpretation is "There may be any number of output assets", based on the wording 'as many assets as it wants'.

But in practice I haven't been able to get two outputs, one of the 'addOutput' invocations seems to have no effect.  Then I noticed 'should immediately throw..', which seems to reinforce the "..at most one.." interpretation.

Maybe the dartdoc could be made more explicit, such that other readers won't experience the same confusion?

**Comment by nex3** [comment]
I think "A transformation can output as many assets as it wants" is pretty explicit, but I suppose we can change "the" to "an" there as well.

I don't know why you're not seeing multiple outputs in your transformation. What are you doing to test it?
